name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure
        run: gcloud auth configure-docker --quiet

      - name: Build
        run: docker build --target prod -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/beatic-backend:${{ github.sha }} -f ./build/api/Dockerfile .

      - name: Push
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/plate-api:${{ github.sha }}

      - name: deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: plate-api
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/plate-api:${{ github.sha }}
          region: asia-northeast1
